spring:
  application:
    name: Rest-With-SpringBoot-Java
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rest_with_springBoot?useTimezone=true&serverTimezone=UTC
    username: root
    password: 247935Fr@
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:       
    show-sql: false
    open-in-view: false
logging:
  level:
   # root: WARN 
    https.github.com.FrancoBorba: DEBUG
